version: '3'

services:
  db:
    container_name: lumen_db
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=core
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=passwd
    networks:
      - core
    ports:
      - 33069:3306
    restart: always
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/

  core:
    container_name: lumen_core
    build: .
    env_file:
      - .env
    networks:
      - core
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./public:/var/www/html/
    ports:
      - 8080:8080

networks:
  core:
